name: Publish

on:
  push:
    branches: 
      - '**'
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: rlespinasse/github-slug-action@v2.x
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build the project
      run: |
        npm run clean
        npm run build
    - name: Run tests
      run: npm run test
    - name: Build Docker image
      run: |
        npm prune --production
        docker build --tag ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }} .
    - name: Publish to DockerHub
      run: docker push ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}

